# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"1\n\x08Metadata\x12\x16\n\x0epayment_intent\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\xe5\x01\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12\x18\n\x10\x64\x65livery_address\x18\x04 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x05 \x01(\x02\x12\x10\n\x08\x64iscount\x18\x06 \x01(\x02\x12\x12\n\nnet_amount\x18\x07 \x01(\x02\x12\x14\n\x0corder_status\x18\x08 \x01(\t\x12\x16\n\x0epayment_status\x18\t \x01(\t\x12!\n\x08metadata\x18\n \x01(\x0b\x32\x0f.order.Metadatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATA._serialized_start=22
  _METADATA._serialized_end=71
  _ORDER._serialized_start=74
  _ORDER._serialized_end=303
# @@protoc_insertion_point(module_scope)
